In [3]:

import cv2
import numpy as np

vid = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier('C:/CVTutorial/haarcascade_frontalface_default.xml')

skip = 0
face_data = []

dataset_path = "C:/CVTutorial/KnnFaces/"

file_name = input('Enter your name : ')

while True:
    ret, frame = vid.read()
    if ret == True:
        frame = cv2.resize(frame, (1280,960), fx=0, fy=0,
                           interpolation = cv2.INTER_CUBIC)
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        faces = face_cascade.detectMultiScale(gray, 1.3, 5)
        
        if len(faces) == 0:
            continue 
        k = 1
        faces = sorted(faces, key = lambda x : x[2]*x[3],reverse = False)
        skip += 1
        
        for face in faces[:1]:
            x, y, w, h = face
            offset = 5
            face_offset = frame[y-offset:y+h+offset, x-offset:x+w+offset]
            face_selection = cv2.resize(face_offset, (150,150))
            
            if skip % 10 == 0:
                face_data.append(face_selection)
                print(len(face_data))
                
            cv2.imshow(str(k), face_selection)
            
            k += 1
            
            cv2.rectangle(frame, (x,y), (x+w, y+h), (255, 255, 255), 2)

        cv2.imshow('faces', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

face_data = np.array(face_data)
face_data = face_data.reshape((face_data.shape[0],-1))
print(face_data)

np.save(dataset_path + file_name, face_data)
print('Dataset saved at : {}'.format(dataset_path + file_name + '.npy'))

vid.release()
cv2.destroyAllWindows()


Enter your name : anant
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
[[ 64  63  65 ... 154 158 149]
 [ 31  29  30 ... 181 176 165]
 [ 23  24  20 ... 187 184 180]
 ...
 [ 33  34  36 ... 196 186 178]
 [ 38  35  35 ... 189 187 172]
 [ 23  27  24 ... 194 181 165]]
Dataset saved at : C:/CVTutorial/KnnFaces/anant.npy
