In [7]:
# Tensorflow is Deep Learning Package
import tensorflow as tf
# Keras is based on Tensorflow & Its High End API
import tensorflow.keras as keras


In [8]:
# scalar with tensor rank = 0 , shape = 0, dtype = int32 Bits
tf.constant(10)

# scalar with tensor rank = 0 , shape = 0, 
const_1 = tf.constant(127, dtype = 'int64')
print(const_1)

const_1.numpy()

const_1.shape


tf.Tensor(127, shape=(), dtype=int64)


TensorShape([])

In [9]:
# Vectors
# Vector with Rank = 1
const_2 = tf.constant([20.,40.,60.,80.,15.,17.], dtype = 'float16')
print(const_2)

const_2 = tf.constant([220, 240, 260, 280, 115, 217], dtype = 'int16')
print(const_2)

# rank = 1
const_2.shape

const_2.numpy()

tf.Tensor([20. 40. 60. 80. 15. 17.], shape=(6,), dtype=float16)
tf.Tensor([220 240 260 280 115 217], shape=(6,), dtype=int16)


array([220, 240, 260, 280, 115, 217], dtype=int16)

In [11]:
# Matrix

# Vector with Rank = 2
const_3 = tf.constant([[220, 230, 120],
                      [310, 431, 321],
                      [120, 130, 1320]], dtype = 'int16')

print(const_3)

const_3.numpy()


tf.Tensor(
[[ 220  230  120]
 [ 310  431  321]
 [ 120  130 1320]], shape=(3, 3), dtype=int16)


array([[ 220,  230,  120],
       [ 310,  431,  321],
       [ 120,  130, 1320]], dtype=int16)

In [13]:
# Tensor N-D Array

const_4 = tf.constant([[[10, 20, 40],
                       [45, 51, 41],
                       [32, 35, 11]],
                     [[13, 21, 41],
                       [41, 52, 42],
                       [31, 36, 23]]], dtype = 'int16')
print(const_4)



tf.Tensor(
[[[10 20 40]
  [45 51 41]
  [32 35 11]]

 [[13 21 41]
  [41 52 42]
  [31 36 23]]], shape=(2, 3, 3), dtype=int16)


In [14]:
var_1 = tf.Variable(0, dtype = 'int8')
print(var_1)

# Variable Vector with Rank = 1
var_2 = tf.Variable([2.,4.,6.,8.,15.,17.], dtype = 'float16')
print(var_2)

# Vector with Rank = 2
var_3 = tf.Variable([[220, 230, 120],
                     [310, 431, 321],
                     [120, 130, 1320]], dtype = 'int16')
print(var_3)

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=0>
<tf.Variable 'Variable:0' shape=(6,) dtype=float16, numpy=array([ 2.,  4.,  6.,  8., 15., 17.], dtype=float16)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int16, numpy=
array([[ 220,  230,  120],
       [ 310,  431,  321],
       [ 120,  130, 1320]], dtype=int16)>


In [17]:
#### Mathematical Operations
# Y = f(WT * X + bias)

# Y = f(WT * X + bias)
Weights = tf.Variable([[10],
                       [12],
                       [16],
                       [19],
                       [9],
                       [11]], dtype = 'float16')
print(Weights)


<tf.Variable 'Variable:0' shape=(6, 1) dtype=float16, numpy=
array([[10.],
       [12.],
       [16.],
       [19.],
       [ 9.],
       [11.]], dtype=float16)>


In [18]:
# Y = WT * X + bias
X = tf.constant([[20],
                 [25],
                 [19],
                 [11],
                 [15],
                 [21]], dtype = 'float16')
print(X)


tf.Tensor(
[[20.]
 [25.]
 [19.]
 [11.]
 [15.]
 [21.]], shape=(6, 1), dtype=float16)


In [19]:
WT = tf.transpose(Weights)

In [21]:
print(WT)

tf.Tensor([[10. 12. 16. 19.  9. 11.]], shape=(1, 6), dtype=float16)


In [25]:
# Y = X * W
tf.tensordot(X, WT, axes=1)



<tf.Tensor: shape=(6, 6), dtype=float16, numpy=
array([[200., 240., 320., 380., 180., 220.],
       [250., 300., 400., 475., 225., 275.],
       [190., 228., 304., 361., 171., 209.],
       [110., 132., 176., 209.,  99., 121.],
       [150., 180., 240., 285., 135., 165.],
       [210., 252., 336., 399., 189., 231.]], dtype=float16)>

In [26]:
tf.tensordot(WT, X, axes=1)


<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[1379.]], dtype=float16)>

In [28]:
import tensorflow.keras as Keras
keras.__version__

'2.9.0'

In [29]:
# Dense Neural Network
from tensorflow.keras.layers import Dense
# Sequential Connection with Neural Network
from tensorflow.keras.models import Sequential
# Optimizers for Regression Model
from tensorflow.keras.optimizers import RMSprop


In [33]:
def build_model():
    # Sequential Neural Network - FeedForward Neural Network
    model = Sequential()
    # units = Number of Neurons (2 * pow(n)), input_shape = Num of Features
    model.add(Dense(units = 16, activation = 'relu', input_shape = [5]))
    # Hidden Layer - I
    model.add(Dense(units = 32, activation = 'relu'))
    # Hidden Layer - II
    model.add(Dense(units = 64, activation = 'relu'))
    # Output Layer
    model.add(Dense(units = 1))
    # Model Compiler
    model.compile(loss = 'mean_squared_error', optimizer = 'RMSprop', metrics = ['mean_squared_error',
                                                                                 'mean_absolute_error'])
    
    return model


In [34]:
model = build_model()

model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 16)                96        
                                                                 
 dense_5 (Dense)             (None, 32)                544       
                                                                 
 dense_6 (Dense)             (None, 64)                2112      
                                                                 
 dense_7 (Dense)             (None, 1)                 65        
                                                                 
Total params: 2,817
Trainable params: 2,817
Non-trainable params: 0
_________________________________________________________________
